#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AutoSystem")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoja(Loja instance);
    partial void UpdateLoja(Loja instance);
    partial void DeleteLoja(Loja instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Model.Properties.Settings.Default.AutoSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Loja> Lojas
		{
			get
			{
				return this.GetTable<Loja>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lojas")]
	public partial class Loja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLoja;
		
		private string _Loja1;
		
		private string _Endereco;
		
		private string _Cep;
		
		private string _UF;
		
		private string _Municipio;
		
		private string _Cidade;
		
		private string _Celular;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLojaChanging(int value);
    partial void OnIdLojaChanged();
    partial void OnLoja1Changing(string value);
    partial void OnLoja1Changed();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCepChanging(string value);
    partial void OnCepChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnMunicipioChanging(string value);
    partial void OnMunicipioChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    #endregion
		
		public Loja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoja", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLoja
		{
			get
			{
				return this._IdLoja;
			}
			set
			{
				if ((this._IdLoja != value))
				{
					this.OnIdLojaChanging(value);
					this.SendPropertyChanging();
					this._IdLoja = value;
					this.SendPropertyChanged("IdLoja");
					this.OnIdLojaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Loja", Storage="_Loja1", DbType="VarChar(255)")]
		public string Loja1
		{
			get
			{
				return this._Loja1;
			}
			set
			{
				if ((this._Loja1 != value))
				{
					this.OnLoja1Changing(value);
					this.SendPropertyChanging();
					this._Loja1 = value;
					this.SendPropertyChanged("Loja1");
					this.OnLoja1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(255)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cep", DbType="VarChar(17)")]
		public string Cep
		{
			get
			{
				return this._Cep;
			}
			set
			{
				if ((this._Cep != value))
				{
					this.OnCepChanging(value);
					this.SendPropertyChanging();
					this._Cep = value;
					this.SendPropertyChanged("Cep");
					this.OnCepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="VarChar(255)")]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this.OnMunicipioChanging(value);
					this.SendPropertyChanging();
					this._Municipio = value;
					this.SendPropertyChanged("Municipio");
					this.OnMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(255)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(17)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
